---
jasypt:
  algorithm: "PBEWITHSHA256AND256BITAES-CBC-BC"
  providerName: "BC"
  password: "curso_grails"
  keyObtentionIterations: 1000
grails:
    mail:
      host:     'smtp.gmail.com'
      port:     465
      username: 'tuuser'
      password: 'tupass'
      props:
        'mail.smtp.auth':                   true
        'mail.smtp.socketFactory.port':     465
        'mail.smtp.socketFactory.class':    'javax.net.ssl.SSLSocketFactory'
        'mail.smtp.socketFactory.fallback': false
    profile: web
    codegen:
        defaultPackage: primer_app_grails
    plugin:
        springsecurity:
            apf:
                postOnly: false
            logout:
                postOnly: false
            userLookup:
                userDomainClassName:    'ejemplo.security.User'
                authorityJoinClassName: 'ejemplo.security.UserRole'
            authority:
                className: 'ejemplo.security.Role'
            controllerAnnotations:
                staticRules:
                    '/':                      ['ROLE_ADMIN','ROLE_NORMAL','ROLE_PUBLISHER']
                    '/**':                    ['ROLE_ADMIN','ROLE_NORMAL','ROLE_PUBLISHER']
                    '/index':                 ['ROLE_ADMIN','ROLE_NORMAL','ROLE_PUBLISHER']
                    '/index.gsp':             ['ROLE_ADMIN','ROLE_NORMAL','ROLE_PUBLISHER']
                    '/assets/**':             permitAll
                    '/**/js/**':              permitAll
                    '/**/css/**':             permitAll
                    '/**/images/**':          permitAll
                    '/**/favicon.ico':        permitAll
                    '/usuario/create':        permitAll
                    '/usuario/save':          permitAll
                    '/user/restore_pass':     permitAll
                    '/user/send_email':       permitAll
                    '/user/change_pass':      permitAll
                    '/user/update_pass':      permitAll


info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

endpoints:
    jmx:
        unique-names: true

dataSource:
    pooled: true
    jmxExport: true
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    driverClassName: com.mysql.jdbc.Driver
    username: 'root'
    password: '1234'

environments:
    development:
        dataSource:
            dbCreate: update #create-drop
            url: jdbc:mysql://localhost/curso_grails #jdbc:h2:file:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE#mem:devDb

    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED


